version: '3'
services:
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: @Password7
      MYSQL_DATABASE: ruralrides
      MYSQL_USER: user
      MYSQL_PASSWORD: @Password7